### ISSUE TITLE
Question about Erlangshen 3.9B

### ISSUE THREAD

**Issue by mx8435** [IDEA-CCNL/Fengshenbang-LM#144]
Hi, thanks for the great job. Is Erlangshen-3.9B model only use data parallelism ? I did not found any model parallelism in Erlangshen code for 3.9B size model. Can you provide the Erlangshen Big model pretraining detail ? Why the script `pretrain_erlangshen_3.9B.sh` has been removed in master ?

**Comment by ganzhiruyi** [comment]
For Erlangshen-3.9B, we use pipeline parallelism + data parallelism for performance based on Megatron-Deepspeed project, because it's complexity we don't opensource the project now, other training detail is same as Erlangshen-1.3B, you can find the model detail from https://huggingface.co/IDEA-CCNL/Erlangshen-MegatronBert-3.9B-Chinese/blob/main/config.json.
